name: cpp-linter as pkg

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'which branch to test'
        default: 'main'
        required: true

jobs:
  cpp-linter:
    runs-on: windows-latest

    strategy:
      matrix:
        clang-version: ['7', '8', '9','10', '11', '12', '13', '14']
        repo: ['cpp-linter/cpp-linter']
        branch: ['${{ inputs.branch }}']
      fail-fast: false

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install workflow deps
        run: python -m pip install clang-tools git+https://github.com/${{ matrix.repo }}/@${{ matrix.branch }}

      - name: Install clang-tools
        run: clang-tools --install ${{ matrix.clang-version }} --directory ${{ runner.temp }}/llvm

      - name: Setup VS dev env
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Cache the build artifacts
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ hashFiles('src/CMakeLists.txt', 'src/demo.cpp', 'src/demo.hpp') }}

      - name: Generate  compiler database
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: mkdir build && cmake -Bbuild src -G "NMake Makefiles"

      - name: Run linter as package
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          cpp-linter 
            -s=file 
            -v=9 
            -i=build 
            -p=build 
            -V=${{ runner.temp }}/llvm 
            -f=false 
            --extra-arg="-std=c++14 -Wall" 
            --thread-comments=${{ matrix.clang-version == '12' }} 
            -a=${{ matrix.clang-version == '12' }}

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1
